In [11]:
import torch
import numpy as np

In [3]:
def describe(x):
    print("타입 : {}".format(x.type()))
    print("크기 : {}".format(x.shape))
    print("값: \n{}".format(x))

In [5]:
describe(torch.Tensor(2, 3))

타입 : torch.FloatTensor
크기 : torch.Size([2, 3])
값: 
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [6]:
describe(torch.rand(2,3))
describe(torch.randn(2,3))

타입 : torch.FloatTensor
크기 : torch.Size([2, 3])
값: 
tensor([[0.7246, 0.8850, 0.3697],
        [0.1023, 0.9770, 0.8203]])
타입 : torch.FloatTensor
크기 : torch.Size([2, 3])
값: 
tensor([[-1.6730,  1.4581,  0.7020],
        [ 0.3173, -0.0142, -0.0775]])


In [8]:
describe(torch.zeros(2,3))
x = torch.ones(2,3)
describe(x)
x.fill_(5)
describe(x)

타입 : torch.FloatTensor
크기 : torch.Size([2, 3])
값: 
tensor([[0., 0., 0.],
        [0., 0., 0.]])
타입 : torch.FloatTensor
크기 : torch.Size([2, 3])
값: 
tensor([[1., 1., 1.],
        [1., 1., 1.]])
타입 : torch.FloatTensor
크기 : torch.Size([2, 3])
값: 
tensor([[5., 5., 5.],
        [5., 5., 5.]])


In [9]:
#파이썬 리스트로 텐서 만들고 초기화하기
x = torch.Tensor([[1, 2, 3],
                  [4, 5, 6]])
describe(x)

타입 : torch.FloatTensor
크기 : torch.Size([2, 3])
값: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [14]:
#넘파이로 텐서 만들고 초기화
npy = np.random.rand(2, 3)
describe(torch.from_numpy(npy))

타입 : torch.DoubleTensor
크기 : torch.Size([2, 3])
값: 
tensor([[0.3164, 0.2570, 0.7285],
        [0.6289, 0.1155, 0.9383]], dtype=torch.float64)


In [15]:
#텐서 속성
x = torch.FloatTensor([[1, 2, 3],
                       [4, 5, 6]])
describe(x)

타입 : torch.FloatTensor
크기 : torch.Size([2, 3])
값: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [17]:
x = x.long()
describe(x)

타입 : torch.LongTensor
크기 : torch.Size([2, 3])
값: 
tensor([[1, 2, 3],
        [4, 5, 6]])
