In [5]:
import torch
import numpy as np

In [6]:
def describe(x):
    print("타입 : {}".format(x.type()))
    print("크기 : {}".format(x.shape))
    print("값: \n{}".format(x))

In [7]:
describe(torch.Tensor(2, 3))

타입 : torch.FloatTensor
크기 : torch.Size([2, 3])
값: 
tensor([[2.0775e+20, 5.2946e+22, 4.2009e-05],
        [2.5932e-09, 2.1746e+23, 2.6255e-06]])


In [8]:
describe(torch.rand(2,3))
describe(torch.randn(2,3))

타입 : torch.FloatTensor
크기 : torch.Size([2, 3])
값: 
tensor([[0.8608, 0.8089, 0.5073],
        [0.1348, 0.2350, 0.8098]])
타입 : torch.FloatTensor
크기 : torch.Size([2, 3])
값: 
tensor([[ 1.2632, -0.9532, -0.4176],
        [ 0.5807, -0.8015, -0.1650]])


In [9]:
describe(torch.zeros(2,3))
x = torch.ones(2,3)
describe(x)
x.fill_(5)
describe(x)

타입 : torch.FloatTensor
크기 : torch.Size([2, 3])
값: 
tensor([[0., 0., 0.],
        [0., 0., 0.]])
타입 : torch.FloatTensor
크기 : torch.Size([2, 3])
값: 
tensor([[1., 1., 1.],
        [1., 1., 1.]])
타입 : torch.FloatTensor
크기 : torch.Size([2, 3])
값: 
tensor([[5., 5., 5.],
        [5., 5., 5.]])


In [9]:
#파이썬 리스트로 텐서 만들고 초기화하기
x = torch.Tensor([[1, 2, 3],
                  [4, 5, 6]])
describe(x)

타입 : torch.FloatTensor
크기 : torch.Size([2, 3])
값: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [14]:
#넘파이로 텐서 만들고 초기화
npy = np.random.rand(2, 3)
describe(torch.from_numpy(npy))

타입 : torch.DoubleTensor
크기 : torch.Size([2, 3])
값: 
tensor([[0.3164, 0.2570, 0.7285],
        [0.6289, 0.1155, 0.9383]], dtype=torch.float64)


In [15]:
#텐서 속성
x = torch.FloatTensor([[1, 2, 3],
                       [4, 5, 6]])
describe(x)

타입 : torch.FloatTensor
크기 : torch.Size([2, 3])
값: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [17]:
x = x.long()
describe(x)

타입 : torch.LongTensor
크기 : torch.Size([2, 3])
값: 
tensor([[1, 2, 3],
        [4, 5, 6]])


In [10]:
x = torch.tensor([[1, 2, 3],
                  [4, 5, 6]], dtype=torch.int64)
describe(x)

타입 : torch.LongTensor
크기 : torch.Size([2, 3])
값: 
tensor([[1, 2, 3],
        [4, 5, 6]])


In [11]:
x = x.float()
describe(x)

타입 : torch.FloatTensor
크기 : torch.Size([2, 3])
값: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [12]:
# 1.4.4 텐서 연산
x = torch.rand(2, 3)
describe(x)

타입 : torch.FloatTensor
크기 : torch.Size([2, 3])
값: 
tensor([[0.3266, 0.2154, 0.9725],
        [0.6990, 0.1019, 0.3490]])


In [13]:
describe(torch.add(x, x))

타입 : torch.FloatTensor
크기 : torch.Size([2, 3])
값: 
tensor([[0.6531, 0.4308, 1.9451],
        [1.3980, 0.2037, 0.6980]])


In [14]:
describe(x+x)

타입 : torch.FloatTensor
크기 : torch.Size([2, 3])
값: 
tensor([[0.6531, 0.4308, 1.9451],
        [1.3980, 0.2037, 0.6980]])


In [29]:
x = torch.arange(6)
describe(x)

타입 : torch.LongTensor
크기 : torch.Size([6])
값: 
tensor([0, 1, 2, 3, 4, 5])


In [30]:
x = x.view(2, 3)
describe(x)

타입 : torch.LongTensor
크기 : torch.Size([2, 3])
값: 
tensor([[0, 1, 2],
        [3, 4, 5]])


In [32]:
describe(torch.sum(x, dim=0))

타입 : torch.LongTensor
크기 : torch.Size([3])
값: 
tensor([3, 5, 7])


In [33]:
describe(torch.sum(x, dim=1))

타입 : torch.LongTensor
크기 : torch.Size([2])
값: 
tensor([ 3, 12])


In [34]:
describe(torch.transpose(x, 0, 1))

타입 : torch.LongTensor
크기 : torch.Size([3, 2])
값: 
tensor([[0, 3],
        [1, 4],
        [2, 5]])


In [35]:
# 1.4.5 인덱싱, 슬라이싱, 연결

x = torch.arange(6).view(2,3)
describe(x)

타입 : torch.LongTensor
크기 : torch.Size([2, 3])
값: 
tensor([[0, 1, 2],
        [3, 4, 5]])


In [20]:
describe(x[:1, :2])

타입 : torch.LongTensor
크기 : torch.Size([1, 2])
값: 
tensor([[0, 1]])


In [24]:
describe(x[0, 1])

타입 : torch.LongTensor
크기 : torch.Size([])
값: 
1


In [25]:
indices = torch.LongTensor([0,2])
describe(torch.index_select(x, dim=1, index=indices))

타입 : torch.LongTensor
크기 : torch.Size([2, 2])
값: 
tensor([[0, 2],
        [3, 5]])


In [37]:
indices = torch.LongTensor([0,0])
describe(torch.index_select(x, dim=0, index=indices))

타입 : torch.LongTensor
크기 : torch.Size([2, 3])
값: 
tensor([[0, 1, 2],
        [0, 1, 2]])


In [38]:
row_indices = torch.arange(2).long()
col_indices = torch.LongTensor([0,1])
describe(x[row_indices, col_indices])

타입 : torch.LongTensor
크기 : torch.Size([2])
값: 
tensor([0, 4])
